### ISSUE TITLE
Medlem ikke fundet når man indtaster nyt resultat

### ISSUE THREAD

**Issue by Joghur** [cph-mn521/Delfinen#3]
Det kan være logikken omkring fejlmeddelsen er forkert

**Comment by cph-mn521** [comment]
Ser ud til at virke. kan være vores kombobox med "disciplin" kun skal indholde den egentlige svømmers disciplin?

**Comment by nfmbang** [comment]
Pt finder den alle svømmere der har de discipliner (og evt andre). 
Den søger ikke efter svømmere med "kun" de discipliner.

**Comment by Joghur** [comment]
Der hentes ikke data fra konkurrencesvømmerne, så Discipliner bliver ikke sat efter der er søgt på een

**Comment by Joghur** [comment]
Lukker pga titel ikke passer med nye problemer. Jeg ved ikke om det er det værd at fixe visning af discipliner
